### ISSUE TITLE
about vertical text !

### ISSUE THREAD

**Issue by goodtogood** [tianzhi0549/CTPN#1]
Hi there,
recently I‘m going to do some tests on text detection，in natural image
I googled a lot and found this great work !
I found that most detections are failure on vertical text after tried some images .
how to train this network and is your dataset  available for downloading and training ?
thanks !
Best regards,

**Comment by tianzhi0549** [comment]
@goodtogood Thank you for your interest. And the method cannot handle vertical text at this point. I suggest that you could rotate your input image by 90 degree and then pass it through the network again.
We're so sorry that we can't release the training data, at least not yet, because of the license of the training data. You can find the training details in our paper.
Thank you very much:-).

**Comment by goodtogood** [comment]
@tianzhi0549 
 Got it , rotation is a good idea !
do you have some plan for updating  source code to support CUDA8.0 && CUDNN 5.0?
thanks for your reply!

**Comment by tianzhi0549** [comment]
@goodtogood I'm sorry, we don't have this plan now. Updating CUDA and CUDNN needs to update the caffe we ship to new version. If you're interested in this, welcome to make a PR on it. Thank you:-).

**Comment by goodtogood** [comment]
OK, I'll have a try !
thanks !
Best regards

**Comment by deshanadesai** [comment]
Hi, as a follow-up to @goodtogood 's question, I want to ask if this code is compatible with Open CV 3 & Cuda version 7.5? I tried compiling it with the additional statement:
```
# Uncomment if you're using OpenCV 3
OPENCV_VERSION := 3
```
in Makefile.config and got a OpenCV-based error.

**Comment by tianzhi0549** [comment]
@deshanadesai The code isn't compatible OpenCV3. Simply to add the statement cannot make #it support opencv3.0. You need to change the Makefile of Caffe. You can find more details (here)[https://github.com/BVLC/caffe/issues/1276]. And I'm not sure if the code can work with CUDA7.5. Probably not. Thank you:-).
