### ISSUE TITLE
How ground truth boxes are generated?

### ISSUE THREAD

**Issue by Arsenal591** [tianzhi0549/CTPN#100]
Let's say there is a text area, `(xmin, ymin, xmax, ymax) = (0, 0, 15, 30)`. So what are the corresponding gt boxes of this text area? Are they just `[(0, 0, 15, 30)]`, or we should keep multiple gt boxes for different anchor sizes, i.e , `[(0, 0, 15, 11), (0, 0, 15, 15), (0, 0, 15, 22), (0, 0, 15, 30)`]?
Thanks a lot!

**Comment by tianzhi0549** [comment]
@Arsenal591 Only one box is needed, which is used to compute overlaps with different anchors. Thank you.

**Comment by Arsenal591** [comment]
Thanks. 
So what if the width of the text area is more than 16 pixels (64 pixels e.g.)?. I guess we should divide the text area into several boxes , and widths of each box are all 16 pixels. Do I get it right?
If that is the case, then how do we divide the text area? For example ,if `(xmin, xmax)=(10, 73)`, do we get `[(10, 25), (26, 41), (42, 57), (58, 73)]` (divided by `xmin+16*i`), or`[(10, 31),(32, 47), (48, 63), (64, 73)]`(divided by `16*i`)?

**Comment by tianzhi0549** [comment]
@Arsenal591 It should be the second case. Thank you.

**Comment by Arsenal591** [comment]
Thanks! Your guidance is very helpful.
