### ISSUE TITLE
Bath size when training LSTM ?

### ISSUE THREAD

**Issue by ThorPham** [tianzhi0549/CTPN#108]
Batch size when training LSTM is H.Are you correct?
 I don't understand why output LSTM is 512xWxH ( why have H in there).Thank so much

**Comment by tianzhi0549** [comment]
@ThorPham The batch size of LSTM should be N x H. As described in our paper, we only consider the *horizontal* context relationship. As a result, the W of feature maps is viewed as T in LSTM, and original N and H are regarded as the batch size of LSTM. Thank you very much.

**Comment by ThorPham** [comment]
Thank you so much. Very clearly
