### ISSUE TITLE
The text_recs returned has a problem

### ISSUE THREAD

**Issue by shuizhongyu** [tianzhi0549/CTPN#112]
If the image is scaled,and the returned  text_recs is scaled too.
But this is not the right text_recs,the right one must be scaled back.

**Comment by tianzhi0549** [comment]
@shuizhongyu It should not be a bug. We use these scaled bounding boxes for visualization purposes. If you want to use them for evaluation, please scale them back by yourself. Thank you very much.

**Comment by shuizhongyu** [comment]
@tianzhi0549  ok,i see,thank you
