### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by HouGall** [tianzhi0549/CTPN#115]
能不能在Windows的CPU上跑？

**Comment by tianzhi0549** [comment]
It should be OK on windows.

**Comment by HouGall** [comment]
谢谢你啦！需要修改什么吗？

**Comment by tianzhi0549** [comment]
@HouGang1 No changes needed for the code. But you may need to change the compiling process of caffe.

**Comment by HouGall** [comment]
好的谢谢啦

**Comment by tianzhi0549** [comment]
You are welcome.
