### ISSUE TITLE
How to prepare my own dataset for CTPN training?

### ISSUE THREAD

**Issue by ICTwangbiao** [tianzhi0549/CTPN#13]
Hi @tianzhi0549 , thanks for your test code and model! I want to train CTPN on my own dataset, but when I prepare annotation xml files, I don't know what each object should be. Is it just like a text proposal(fixed width:16px, precompute its coordinate from a whole word bounding box) or a whole word bounding box(like ICDAR 2013 annotations)? Thanks.

**Comment by tianzhi0549** [comment]
@ICTwangbiao Thank you for your interest. I think what annotations in your xml files is up to you. You could compute these ground truths of text proposals on the fly or pre-compute them in advance. Thank you:-).

**Comment by ICTwangbiao** [comment]
@tianzhi0549 thank you very much.
