### ISSUE TITLE
Changes to caffe comparing to the official one?

### ISSUE THREAD

**Issue by qingswu** [tianzhi0549/CTPN#18]
Is it possible to list the major changes to this version of caffe you use? I want know the potential issues/conflict while merging it with the newer version of caffe.

My GPU has to run with CUDA 8.0, which is not compatible this version of caffe.

**Comment by tianzhi0549** [comment]
@qingswu Thank you for your interest. The caffe is based on an older caffe. We added some layers (transpose, reverse, lstm) to it. If you want to merge it with the latest caffe, you can migrate these layers. Thank you:-).

**Comment by KeyKy** [comment]
@tianzhi0549 Do you only change the transpose, reverse, lstm layers?

**Comment by qingswu** [comment]
@KeyKy you can check out my fork at https://github.com/qingswu/CTPN and the log info of the forked caffe.

**Comment by tianzhi0549** [comment]
@qingswu Thank you for your upgrading:-).

**Comment by myme5261314** [comment]
@tianzhi0549 
Is it ok that you could tell which commit SHA-ID you diverse from the official Caffe repo? Missing all the git info of `caffe` folder is such inconvenient to merge further upgrade commits from official Caffe to support some new features (CUDA 8.0/ Opencv 3.0+).

So, maybe what we need is just a SHA-ID of your diverse commit point, the rest of the work should be using merge I guess.

**Comment by DuinoDu** [comment]
@qingswu , much thanks for your upgrading~

**Comment by TheShadow29** [comment]
@qingswu can you briefly explain how you added the layers (Reverse, transpose and Lstm) to caffe. I tried working with your forked repo, but it still gives me `ImportError: No module named _caffe'. I would rather use my pre-installed caffe and perhaps add the layers to them. Thanks

**Comment by hqliling** [comment]
have you added the layers (Reverse, transpose and Lstm) to caffe?@qingswu

**Comment by szbach** [comment]
@qingswu (i also use CUDA8...)  i got your repository and update caffe with the latest version. After running make -j && make pycaffe. finaly,  i got the error message as follows :
src/caffe/layers/lstm_layer_1.cpp: In instantiation of ‘void caffe::LstmLayer<Dtype>::Backward_cpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = float]’:
src/caffe/layers/lstm_layer_1.cpp:314:1:   required from here
src/caffe/layers/lstm_layer_1.cpp:253:20: error: ‘caffe_bound’ was not declared in this scope
         caffe_bound(4*H_, pre_gate_diff_t, -clipping_threshold_,
                    ^
src/caffe/layers/lstm_layer_1.cpp: In instantiation of ‘void caffe::LstmLayer<Dtype>::Backward_cpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = double]’:
src/caffe/layers/lstm_layer_1.cpp:314:1:   required from here
src/caffe/layers/lstm_layer_1.cpp:253:20: error: ‘caffe_bound’ was not declared in this scope
Makefile:518: recipe for target '.build_release/src/caffe/layers/lstm_layer_1.o' failed
make: *** [.build_release/src/caffe/layers/lstm_layer_1.o] Error 1
make: *** Waiting for unfinished jobs....
src/caffe/layers/infogain_loss_layer.cpp: In instantiation of ‘void caffe::InfogainLossLayer<Dtype>::LayerSetUp(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = float]’:
src/caffe/layers/infogain_loss_layer.cpp:221:1:   required from here
src/caffe/layers/infogain_loss_layer.cpp:18:3: error: ‘const class caffe::InfogainLossParameter’ has no member named ‘axis’
   softmax_param->set_axis(this->layer_param_.infogain_loss_param().axis());
   ^
src/caffe/layers/infogain_loss_layer.cpp: In instantiation of ‘void caffe::InfogainLossLayer<Dtype>::Reshape(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = float]’:
src/caffe/layers/infogain_loss_layer.cpp:221:1:   required from here
src/caffe/layers/infogain_loss_layer.cpp:55:18: error: ‘const class caffe::InfogainLossParameter’ has no member named ‘axis’
   infogain_axis_ =
                  ^
src/caffe/layers/infogain_loss_layer.cpp: In instantiation of ‘void caffe::InfogainLossLayer<Dtype>::LayerSetUp(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = double]’:
src/caffe/layers/infogain_loss_layer.cpp:221:1:   required from here
src/caffe/layers/infogain_loss_layer.cpp:18:3: error: ‘const class caffe::InfogainLossParameter’ has no member named ‘axis’
   softmax_param->set_axis(this->layer_param_.infogain_loss_param().axis());
   ^
src/caffe/layers/infogain_loss_layer.cpp: In instantiation of ‘void caffe::InfogainLossLayer<Dtype>::Reshape(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = double]’:
src/caffe/layers/infogain_loss_layer.cpp:221:1:   required from here
src/caffe/layers/infogain_loss_layer.cpp:55:18: error: ‘const class caffe::InfogainLossParameter’ has no member named ‘axis’
   infogain_axis_ =
                  ^
Makefile:518: recipe for target '.build_release/src/caffe/layers/infogain_loss_layer.o' failed
make: *** [.build_release/src/caffe/layers/infogain_loss_layer.o] Error 1
any advice? many thanks.

**Comment by dm0288** [comment]
> @qingswu Thank you for your interest. The caffe is based on an older caffe. We added some layers (transpose, reverse, lstm) to it. If you want to merge it with the latest caffe, you can migrate these layers. Thank you:-).

@tianzhi0549 How can we migrate layers(reverse, lstm, transpose) to other caffe? Could you please suggest the way to do it?

Thanks.

**Comment by tianzhi0549** [comment]
@dm02 You just need to move the class definition of these layers in header files and their implementation in cpp files. This tutorial (https://github.com/BVLC/caffe/wiki/Development) for developing a new caffe layer might be useful to you. Thank you!

**Comment by dm0288** [comment]
> @dm02 You just need to move the class definition of these layers in header files and their implementation in cpp files. This tutorial (https://github.com/BVLC/caffe/wiki/Development) for developing a new caffe layer might be useful to you. Thank you!

Thanks for your response. I was wondering if I can use this CTPN repository with caffe(BVLC repository) installed with CUDA8.0 and cudnnv6. Will this tutorial help with that?

**Comment by tianzhi0549** [comment]
@dm02 after moving these layers into official caffe, you can use CTPN with it. Thank you.

**Comment by dm0288** [comment]
@tianzhi0549 
While following the procedure I am getting the following error and I am not able find any solution for it .

./include/caffe/loss_layers.hpp:97:47: error: no matching function for call to ‘caffe::AccuracyParameter::ignore_label(int&) const’
       if (label==accuracy_param.ignore_label(i)) {
                                               ^
In file included from ./include/caffe/util/cudnn.hpp:8:0,
                 from ./include/caffe/util/device_alternate.hpp:40,
                 from ./include/caffe/common.hpp:19,
                 from ./include/caffe/blob.hpp:8,
                 from ./include/caffe/layer.hpp:8,
                 from src/caffe/layers/accuracy_layer.cpp:6:
.build_release/src/caffe/proto/caffe.pb.h:17379:34: note: candidate: google::protobuf::int32 caffe::AccuracyParameter::ignore_label() const
 inline ::google::protobuf::int32 AccuracyParameter::ignore_label() const {
                                  ^
.build_release/src/caffe/proto/caffe.pb.h:17379:34: note:   candidate expects 0 arguments, 1 provided

Thanks.

**Comment by tianzhi0549** [comment]
@dm02 Try to change all `label==accuracy_param.ignore_label(i)` to `label==accuracy_param.ignore_label()`.

**Comment by dm02** [comment]
@tianzhi0549  Thanks for your immediate response.
However after fixing the above problem, the following error is coming.

CXX src/caffe/layers/accuracy_layer.cpp
In file included from ./include/caffe/common_layers.hpp:12:0,
                 from ./include/caffe/vision_layers.hpp:10,
                 from src/caffe/layers/accuracy_layer.cpp:9:
./include/caffe/loss_layers.hpp: In member function ‘bool caffe::AccuracyLayer<Dtype>::is_ignore_label(int)’:
./include/caffe/loss_layers.hpp:96:36: error: ‘const class caffe::AccuracyParameter’ has no member named ‘ignore_label_size’
     for (int i=0; i<accuracy_param.ignore_label_size(); i++) {
                                    ^
src/caffe/layers/accuracy_layer.cpp: In instantiation of ‘void caffe::AccuracyLayer<Dtype>::LayerSetUp(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = float]’:
src/caffe/layers/accuracy_layer.cpp:127:1:   required from here
src/caffe/layers/accuracy_layer.cpp:19:60: error: ‘const class caffe::AccuracyParameter’ has no member named ‘ignore_label_size’
     this->layer_param_.accuracy_param().ignore_label_size()>0;
                                                            ^
src/caffe/layers/accuracy_layer.cpp: In instantiation of ‘void caffe::AccuracyLayer<Dtype>::LayerSetUp(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = double]’:
src/caffe/layers/accuracy_layer.cpp:127:1:   required from here
src/caffe/layers/accuracy_layer.cpp:19:60: error: ‘const class caffe::AccuracyParameter’ has no member named ‘ignore_label_size’
Makefile:591: recipe for target '.build_release/src/caffe/layers/accuracy_layer.o' failed
make: *** [.build_release/src/caffe/layers/accuracy_layer.o] Error 1
