### ISSUE TITLE
scripts for training

### ISSUE THREAD

**Issue by Adesun** [tianzhi0549/CTPN#2]
Hi, there
I saw the  result of  Challenge "Focused Scene Text", CTPN  is great .
now I wanna do a full evaluation of CTPN on my own dataset,
is there some related script for training that could be shared?
thx!

**Comment by tianzhi0549** [comment]
Hi @Adesun, Thank you for your interest in CTPN. Currently, we do not release the training codes, due to our industry collaborations. I'm so sorry. You could find training details in our paper. Thank you.

**Comment by Adesun** [comment]
@tianzhi0549  
I see, thanks !
