### ISSUE TITLE
"caffe.LayerParameter" has no field named "transpose_param"

### ISSUE THREAD

**Issue by mahaling** [tianzhi0549/CTPN#20]
I am trying to run the demo.py file and getting the following error. 
Is there something wrong that I am doing. I have the BVLC version of caffe also installed in a different location.

This is the error I am getting while trying to run demo.py 

WARNING: Logging before InitGoogleLogging() is written to STDERR
W0104 15:27:11.308679 30453 _caffe.cpp:154] DEPRECATION WARNING - deprecated use of Python interface
W0104 15:27:11.308717 30453 _caffe.cpp:155] Use this instead (with the named "weights" parameter):
W0104 15:27:11.308722 30453 _caffe.cpp:157] Net('models/deploy.prototxt', 1, weights='models/ctpn_trained_model.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 387:19: Message type "caffe.LayerParameter" has no field named "transpose_param".
F0104 15:27:11.310125 30453 upgrade_proto.cpp:79] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: models/deploy.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by tianzhi0549** [comment]
@mahaling I think you may import other caffe instead of the one we ship. You can use `print caffe` after `import caffe` to see which caffe you're using. Thank you:-).

**Comment by ld909** [comment]
@tianzhi0549  I met the same problem. Please help

**Comment by tianzhi0549** [comment]
@ld909 Please make sure that you import the correct caffe. Thank you:-).

**Comment by mahaling** [comment]
@tianzhi0549 You are right. I just had to point the code to the right version of caffe and it worked!.

**Comment by sabirdvd** [comment]
@mahaling Already have Caffe installed, do I need to reinstall it with the modified version ???

**Comment by yingning** [comment]
@mahaling @tianzhi0549 ,would you mind telling me how you set your caffe_root,  I set my caffe_root ='/home/jsj/CTPN/caffe/python/caffe' ,and I got the follow error :+1: 

"Connected to pydev debugger (build 171.4694.38)
WARNING: Logging before InitGoogleLogging() is written to STDERR
<module 'caffe' from '/home/jsj/caffe/python/caffe/__init__.pyc'>
W0626 13:30:38.482167 12282 _caffe.cpp:122] DEPRECATION WARNING - deprecated use of Python interface
W0626 13:30:38.482203 12282 _caffe.cpp:123] Use this instead (with the named "weights" parameter):
W0626 13:30:38.482208 12282 _caffe.cpp:125] Net('/home/jsj/CTPN/models/deploy.prototxt', 1, weights='/home/jsj/CTPN/models/ctpn_trained_model.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 387:19: Message type "caffe.LayerParameter" has no field named "transpose_param".
F0626 13:30:38.484434 12282 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /home/jsj/CTPN/models/deploy.prototxt
*** Check failure stack trace: ***"

**Comment by mahaling** [comment]
@sabirdvd Yes you need to point the CAFFE_ROOT to the caffe version that comes along with this code. 

@yingning You are doing it right. However, I set the CAFFE_ROOT inside my python code so that it uses that version of caffe. Your code is still referring to the other caffe version that you already have.

**Comment by IfengWangZ** [comment]
i have the same quetion,and the result of command "print caffe" is <module 'caffe' from 'caffe/__init__.py'>

**Comment by IfengWangZ** [comment]
> i have the same quetion,and the result of command "print caffe" is <module 'caffe' from 'caffe/**init**.py'>

ummm, i compile the caffe with cuda8 and cudnn7
