### ISSUE TITLE
HOW to run this code

### ISSUE THREAD

**Issue by eslambakr** [tianzhi0549/CTPN#27]
at first thank you   tianzhi0549   for your great work 
I try to run this code but i cant ,and it seems that there are a lot of people who could run it so i need help please
if any one can write the steps in clearer way or make video with the steps i will be very grateful for him 
and for example i am very confusing should i install caffe or the caffe in the CTPN folder is enough and another a lot of questions so if any one could help me with the steps i will be really grateful

**Comment by tianzhi0549** [comment]
@eslambakr You should install the Caffe here. Please post your problems here in detail. I am very happy to help you if I know the answers. Thank you:-).

**Comment by eslambakr** [comment]
i need clear steps , i will tell you my steps and correct it to me
1-i create a new folder under name "text"
2- clone the repository
3- install python 2.7 then install caffe all that in the "text" folder 
    so the folder now contain (CTPN+Python2.7+caffe)
4-i dont know in which folder should i run this :
    for req in $(cat requirements.txt); do pip install $req; done
    in CPTN or in the installed caffe?
5-i dont know where to run this too 
    cp Makefile.config.example Makefile.config
    as i have two now one in the CTPN and one in the installed caffe too.
6-when i run( make all+make test+make runtest) = i have errors 
so i need the right steps please ,correct it to me 
note there is no need for cuda because i will run it on CPU
thanks a lot for your support

**Comment by tianzhi0549** [comment]
@eslambakr You should run all commands of Caffe installation in the folder caffe of this code. And you can ignore the errors when running `make runtest`. Thank you:-).

**Comment by eslambakr** [comment]
i am very sorry , i still cant run it so i download anaconda2 can you till me the steps using anaconda please
Thank you:-)

**Comment by eslambakr** [comment]
when i run ( make all )  in the your caffe i got this error:

PROTOC src/caffe/proto/caffe.proto
make: protoc: Command not found
make: *** [.build_release/src/caffe/proto/caffe.pb.h] Error 127

**Comment by eslambakr** [comment]
now i am using your docker-file ,it is awesome ,but unfortunately i have this error :
Step 14/31 : ADD cudnn-7.0-linux-x64-v3.0.8-prod.tgz /
lstat cudnn-7.0-linux-x64-v3.0.8-prod.tgz: no such file or directory

**Comment by eslambakr** [comment]
i am using the docker file it is amazing 
and finally it has been finished (Successfully built)
now how can i run it ?what is the next step ?
i type: sudo docker run text   (i choose the name of the image to be text)
but it doesn’t make any changes

**Comment by eslambakr** [comment]
i think i can run it but a new error appear :
Traceback (most recent call last):
  File "demo.py", line 22, in <module>
    from other import draw_boxes, resize_im, CaffeModel
ImportError: No module named other

**Comment by eslambakr** [comment]
i have a new error now :
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0320 18:48:39.929175     9 common.cpp:103] Cannot create Cublas handle. Cublas won't be available.
E0320 18:48:39.934922     9 common.cpp:110] Cannot create Curand generator. Curand won't be available.
F0320 18:48:39.943051     9 common.cpp:141] Check failed: error == cudaSuccess (30 vs. 0)  unknown error
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by varun-suresh** [comment]
You have to use (nvidia-docker)[https://github.com/NVIDIA/nvidia-docker].

**Comment by Huxwell** [comment]
eslambak, I get the same error (ImportError: No module named other) as you with nvidia-docker. How have you dealt with it?
