### ISSUE TITLE
Use without GPU

### ISSUE THREAD

**Issue by Johndirr** [tianzhi0549/CTPN#3]
Is there any way to use this without a GPU?

**Comment by tianzhi0549** [comment]
@Johndirr It's possible. But the reverse layer of CPU (less than 100 lines of code) needs to be implemented. Because most of CPU layers are unoptimized, CPU version is extremely slow. We really don't recommend that.

**Comment by zimenglan-sysu-512** [comment]
@tianzhi0549 can you explain what your `reverse layer` do? thanks.
