### ISSUE TITLE
How to run faster?

### ISSUE THREAD

**Issue by anhhoangta** [tianzhi0549/CTPN#32]
Hi,

I'm currently successful on demo with --no-gpu. The result was so great. But it was slow, so I deployed it in AWS p2.xlarge with 1 GPU. My problem is that if I use CUDA 7 + CuDNN 3.0 as you used, I can't connect it with other works such as text recognition, which I often build in tensorflow because tensorlow can't run in CuDNN 3.0. 

So do you have any version of this code in new CUDA+CuDNN version? Or do you have any version of this in other platforms: tensorflow, keras,...? If not, I will port it into other platforms, so are you ready to help me if I get problems?

Anyway, thanks for your work, excellent!

**Comment by tianzhi0549** [comment]
@anhhoangta I suggest that you could install CUDA 7.0 + CUDNN 3.0 in a different directory and then change the `CUDA_DIR` in Makefile.config of Caffe to compile Caffe with the CUDA + CUDNN. Thank you:-).

**Comment by anhhoangta** [comment]
So did you mean I can't install many version of CUDA toolkit + CuDNN in one machine? I google many times but can't find any discussion about it.

**Comment by tianzhi0549** [comment]
@anhhoangta I mean you CAN install the two versions of CUDA + CUDNN on one machine.

**Comment by anhhoangta** [comment]
Thanks for all!
