### ISSUE TITLE
Question about mapping Text proposal from the network on the image

### ISSUE THREAD

**Issue by thisismohitgupta** [tianzhi0549/CTPN#34]
In my implementation suppose I input an image with dims as (350, 350, 3) and after the last fully convolutional  layer which outputs (N, Spacial Height, Spacial Width, 2, K anchors). In my case the output turns out to be (N, 10, 10, 2, 10). My question how do you map this on the image because for each text proposal in the output it turns out to be of 35X35 pixels in the input image simply dividing (350/10). I dont understand how 16px width is worked out in input image because the coordinates are predicted for the each spacial location which is 35X35 and the horizontal location is fixed to 0 relative to the position of the text proposal. I have been implementing this reading your paper and it would be really great of you if you teach this little doubt of mine so I can compare the performance. Also a really nice research.

**Comment by thisismohitgupta** [comment]
Solved this. Thanks anyways.

**Comment by dajiangxiaoyan** [comment]
@thisismohitgupta  do you mind to give more detail info about this. I also have this confusion.

**Comment by hcnhatnam** [comment]
@dajiangxiaoyan The size of the last fully convolutional layer is not fixed depending on the input image
