### ISSUE TITLE
Side-refinement Exclusion

### ISSUE THREAD

**Issue by deshanadesai** [tianzhi0549/CTPN#4]
Hi @tianzhi0549 ,

First of all, excellent work! You have mentioned in your paper that side-refinement improves the performance on SWT and multi-lingual datasets by 2%. Would you be including this step in your code anytime soon or is it to remain excluded?

Thanks,
Deshana

**Comment by tianzhi0549** [comment]
@deshanadesai Thank you for your comments. We may release this part later.

**Comment by deshanadesai** [comment]
Thanks for the info!

**Comment by wkal** [comment]
@tianzhi0549  I have the same question as @deshanadesai , could you share the training part of the CTPN?  Thanks very much!
