### ISSUE TITLE
when make, generating cpu_nms.c is wrong?

### ISSUE THREAD

**Issue by clscy** [tianzhi0549/CTPN#41]
hi.
I compile it with CPU, but in the fourth step, I compile some cython files in the root directory, this is a warning of make.
it is warning:

cython src/utils/cpu_nms.pyx
gcc -shared -pthread -fPIC -fwrapv -O2 -Wall -fno-strict-aliasing \
	-I/usr/include/python2.7 -o src/utils/cpu_nms.so src/utils/cpu_nms.c
In file included from /usr/include/python2.7/numpy/ndarraytypes.h:1777:0,
                 from /usr/include/python2.7/numpy/ndarrayobject.h:18,
                 from /usr/include/python2.7/numpy/arrayobject.h:4,
                 from src/utils/cpu_nms.c:435:
/usr/include/python2.7/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
rm -rf src/utils/cpu_nms.c

I hope to get your help. thanks.

**Comment by yingning** [comment]
I have the same warnings after  I changed  the Makefile line "-I/usr/include/python2.7" into "-I/home/jsj/anaconda2/lib/python2.7/site-packages/numpy/core/include \ -I/home/jsj/anaconda2/include/python2.7 "  And the address "-I/home/jsj/anaconda2/lib/python2.7/site-packages/numpy/core/include \ -I/home/jsj/anaconda2/include/python2.7"  is part of my  PYTHON_INCLUDE path. I get the following warning:
cython src/utils/cpu_nms.pyx
gcc -shared -pthread -fPIC -fwrapv -O2 -Wall -fno-strict-aliasing \
		-I/home/jsj/anaconda2/lib/python2.7/site-packages/numpy/core/include \
-I/home/jsj/anaconda2/include/python2.7 -o src/utils/cpu_nms.so src/utils/cpu_nms.c
In file included from /home/jsj/anaconda2/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1788:0,
                 from /home/jsj/anaconda2/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/jsj/anaconda2/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from src/utils/cpu_nms.c:274:
/home/jsj/anaconda2/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from /home/jsj/anaconda2/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:27:0,
                 from /home/jsj/anaconda2/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from src/utils/cpu_nms.c:274:
/home/jsj/anaconda2/lib/python2.7/site-packages/numpy/core/include/numpy/__multiarray_api.h:1448:1: warning: ‘_import_array’ defined but not used [-Wunused-function]
 _import_array(void)
 ^
rm -rf src/utils/cpu_nms.c.

Your kind heart will be appreciated,thanks in advance!

**Comment by yingning** [comment]
@tianzhi0549

**Comment by clscy** [comment]
even though there is the warning, the fifth step python tools/demo.py --no-gpu also run successfully.
