### ISSUE TITLE
Is it possible to predict the text?

### ISSUE THREAD

**Issue by JafferWilson** [tianzhi0549/CTPN#50]
Hi,
I have seen the demo of the repository, and I love it. I want to use it in my project. I would like to know whether it is possible at all to predict the text from the boxe? It will be awsome if the project detects the text and predict what it detects.
Kindly, share your view.

**Comment by tianzhi0549** [comment]
@JafferWilson I am sorry that the project is unable to recognize the text it detects. It is another topic called text recognition.

**Comment by JafferWilson** [comment]
Thank you for your humble reply. May I know whether you will include that in future or you are about to or you won't include it at all? May I know.

**Comment by tianzhi0549** [comment]
@JafferWilson We won't include it in the future. The method focuses on text detection only.

**Comment by JafferWilson** [comment]
Ok thank you for your words.
