### ISSUE TITLE
from utils.cpu_nms import cpu_nms as nms ImportError: ./src/utils/cpu_nms.so: undefined symbol: PyFPE_jbuf

### ISSUE THREAD

**Issue by charan223** [tianzhi0549/CTPN#72]
charan/CTPN$ python tools/demo.py 
Traceback (most recent call last):
  File "tools/demo.py", line 24, in <module>
    from detectors import TextProposalDetector, TextDetector
  File "./src/detectors.py", line 4, in <module>
    from utils.cpu_nms import cpu_nms as nms
ImportError: ./src/utils/cpu_nms.so: undefined symbol: PyFPE_jbuf

Running in a virtual anaconda environment and i am using same python

**Comment by leoyhr** [comment]
Same issue here, have you solved it?

**Comment by charan223** [comment]
Yeah solved it....use any one environment to install caffe....total anaconda or total python

**Comment by leoyhr** [comment]
You mean, if i choose anaconda, i have to delete the system default python and re-make caffe?

**Comment by charan223** [comment]
You dont need to delete it....install every package required for caffe through anaconda....using a virtual environment helps

**Comment by leoyhr** [comment]
I have just solved this by specifying the 'include' path in Makefile to my conda environment. Thx a lot!
