### ISSUE TITLE
make error ' build_release/tools/test_net’ is not a directory'

### ISSUE THREAD

**Issue by idefix92** [tianzhi0549/CTPN#74]
Can somebody please help me on that? Really weird... I don't know how to approach the problem..

ln: target ‘.build_release/tools/net_speed_benchmark’ is not a directory
make: *** [.build_release/tools/net_speed_benchmark] Error 1
make: *** Waiting for unfinished jobs....
ln: target ‘.build_release/tools/test_net’ is not a directory
make: *** [.build_release/tools/test_net] Error 1

**Comment by tianzhi0549** [comment]
@idefix92 Could you tell me what commands you execute when encountering this error?

**Comment by idefix92** [comment]
@tianzhi0549 I am executing 'make -j'. I thought that 'sudo make-j' could solve the problem but I am afraid that the caffe u ship will interfere with the overall caffe on my computer.

**Comment by idefix92** [comment]
@tianzhi0549 I found the issue. Seems like my directory path was too long. Thanks anyway!
