### ISSUE TITLE
can't compile caffe with cudnn5

### ISSUE THREAD

**Issue by junedgar** [tianzhi0549/CTPN#9]
Dear tianzhi,
I tried to compile the caffe with the cudnn5, cuda7.5, but i get the errors below:
`**/data/zhengjunjun/deeplearning/CTPN/caffe/include/caffe/util/cudnn.hpp(123): error: argument of type "int" is incompatible with parameter of type "cudnnNanPropagation_t"

/data/zhengjunjun/deeplearning/CTPN/caffe/include/caffe/util/cudnn.hpp(123): error: too few arguments in function call

/data/zhengjunjun/deeplearning/CTPN/caffe/include/caffe/util/cudnn.hpp(123): error: argument of type "int" is incompatible with parameter of type "cudnnNanPropagation_t"

/data/zhengjunjun/deeplearning/CTPN/caffe/include/caffe/util/cudnn.hpp(123): error: too few arguments in function call

/data/zhengjunjun/deeplearning/CTPN/caffe/include/caffe/util/cudnn.hpp(123): error: argument of type "int" is incompatible with parameter of type "cudnnNanPropagation_t"

/data/zhengjunjun/deeplearning/CTPN/caffe/include/caffe/util/cudnn.hpp(123): error: too few arguments in function call

/data/zhengjunjun/deeplearning/CTPN/caffe/include/caffe/util/cudnn.hpp(123): error: argument of type "int" is incompatible with parameter of type "cudnnNanPropagation_t"

/data/zhengjunjun/deeplearning/CTPN/caffe/include/caffe/util/cudnn.hpp(123): error: too few arguments in function call

/data/zhengjunjun/deeplearning/CTPN/caffe/include/caffe/util/cudnn.hpp(123): error: argument of type "int" is incompatible with parameter of type "cudnnNanPropagation_t"

/data/zhengjunjun/deeplearning/CTPN/caffe/include/caffe/util/cudnn.hpp(123): error: too few arguments in function call

2 errors detected in the compilation of "/tmp/tmpxft_0000c829_00000000-5_reduction_layer.cpp4.ii".
CMake Error at cuda_compile_generated_reduction_layer.cu.o.cmake:264 (message):
  Error generating file
 /data/zhengjunjun/deeplearning/CTPN/caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_reduction_layer.cu.o
make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_reduction_layer.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
2 errors detected in the compilation of "/tmp/tmpxft_0000c811_00000000-5_embed_layer.cpp4.ii".**`

Do you have some ideas for these errors？
thank you!

**Comment by tianzhi0549** [comment]
@junedgar, as said in #8, the fastest way to solve the problem is to not use CUDNN. Thank you.
